project_name: goveal
builds:
  - id: goveal
    main: ./cmd/goveal/
    binary: goveal
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: arm
        goarm: '7'

release:
  gitea:
    owner: prskr
    name: goveal
  mode: replace

kos:
  - id: goveal
    build: goveal
    base_image: gcr.io/distroless/static:nonroot
    repository: code.icb4dc0.de/prskr/goveal
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - '{{.Tag}}'
    bare: true
    base_import_paths: true

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
