project_name: goveal
builds:
  - main: ./cmd/goveal/
    binary: goveal
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: arm
        goarm: '7'

dockers:
  - id: goveal
    goos: linux
    goarch: amd64
    goarm: ''
    ids:
      - goveal
    image_templates:
      - ghcr.io/baez90/goveal:{{ .Tag }}
      - ghcr.io/baez90/goveal:{{ .Major }}
    dockerfile: ./build/docker/goveal.dockerfile

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
