---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.io/golang
    tag: 1.19-buster

inputs:
  - name: repo
    path: .

params:
  GO111MODULE: "on"
  CGO_ENABLED: "1"
  GITEA_TOKEN: ((gitea-credentials.token))

run:
  path: bash
  args:
    - -ce
    - |
      go install gotest.tools/gotestsum@latest
      gotestsum -f pkgname-and-test-fails -- -race -shuffle=on ./...
