---
resources:
  - name: daily
    type: time
    source:
      interval: 24h
  - name: goveal.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/goveal.git
  - name: templates.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/pipeline-templates.git

jobs:
  - name: renovate
    plan:
      - get: goveal.git
        trigger: true
      - get: templates.git
      - get: daily
        trigger: true
      - task: renovate
        file: templates.git/tasks/renovate.yml
        input_mapping: { repo: goveal.git }
        vars:
          project_path: prskr/goveal
