name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Install Task
        uses: arduino/setup-task@v1
      
      - name: Build & test
        run: task download-assets test
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
